### ISSUE TITLE
Running autoheal w/o Kubernetes

### ISSUE THREAD

**Issue by fajfer** [openshift/autoheal#110]
Why is using k8s a must here? I have a Prometheus and AWX and I'd like it to simply run playbooks according to alerts but autoheal enforces me to use kubernetes also. Shouldn't some workaround be possible?

**Comment by cben** [comment]
Hi.
Well, we started this project for the specific purpose of monitoring Openshift clusters (informed by existing practices by red hat's ops team).
The 2 scenarios we were debating and wanted to support both were running inside the monitored cluster, or from another cluster.
We simply never considered entirely other uses :-)

I think(?) the dependence on k8s is not strong, it's mostly just how we documented deploying it, and non-essential things like ability to read awx creds from a k8s secret...
PRs welcome :-)

I should also mention this project is somewhat dormant - we'd still like to carry it forward, but nobody is actively assigned to work on it now.

**Comment by fajfer** [comment]
> I think(?) the dependence on k8s is not strong, it's mostly just how we documented deploying it, and non-essential things like ability to read awx creds from a k8s secret...

Yeah, I thought the same. Until autoheal demanded kubernetes config from me. If it was optional and ran without it I wouldn't care much - but it doesn't run without k8s at all (and I'm not much familiar with it, too)

It sounds like I need to dive into the Go and do something myself. It doesn't sound like I'll create a production stable environment though :)

**Comment by fajfer** [comment]
Could I provide autoheal a kube config that might, perhaps, just let me go and test autoheal with prometheus and AWX alone?

**Comment by cben** [comment]
>  It doesn't sound like I'll create a production stable environment though :)

To be clear, this is NOT a battle-tested project.  There were some internal deployment for SREs to play with, but AFAIK nobody used this yet to on real production problems.
We don't have experience to asses how buggy autoheal itself is :see_no_evil:, let alone how it fares under heavy load, what happens when parts of the chain (prometheus/alertmanager/autoheal/awx) crash & restart etc...
*Caveat user ;)*

**Comment by cben** [comment]
peeked at the code.
hmm, https://github.com/openshift/autoheal/blob/master/pkg/batchrunner/batch_action_runner.go actually relies on k8s to run the healing actions in pods (don't remember how exactly, cf #82).
https://github.com/openshift/autoheal/blob/master/pkg/awxrunner/awx_action_runner.go doesn't need k8s.
but as currently structured, the code requires k8s client and passes it through several objects, would need refactoring...

**Comment by fajfer** [comment]
Yeah I was tinkering with the code since this morning but it looks like too much of a challenge for a single man that's not exactly familar with the code and/or project itself :(
