### ISSUE TITLE
Avoid compiling and running the tests of `tools`

### ISSUE THREAD

**Issue by jhernand** [openshift/autoheal#15]
The `tools` directory of the project contains the source of some tools that have been copied from the `openshift/release` project, as decribed [here](https://github.com/openshift/release/tree/master/tools/hack/golang). A side effect of that is that when running `make check` the build scripts try to compile also the tests of those tools, in particular the tests of the `junitreport` tool. That fails because of missing dependencies:

```
tools/junitreport/pkg/builder/flat/test_suites_builder.go:4:2: cannot find package "github.com/openshift/origin/tools/junitreport/pkg/api" in any of:
	/files/projects/openshift/autoheal/_output/local/go/src/github.com/openshift/autoheal/vendor/github.com/openshift/origin/tools/junitreport/pkg/api (vendor tree)
	/usr/lib/golang/src/github.com/openshift/origin/tools/junitreport/pkg/api (from $GOROOT)
	/files/projects/openshift/autoheal/_output/local/go/src/github.com/openshift/origin/tools/junitreport/pkg/api (from $GOPATH)
```

Currently we solved this removing those tests files from the repository, but that isn't a good long term solution, as the tests may be accidentally re-added when the `tools` directory is updated in the future.

A possible solution suggested by @ironcladlou in #6 is to tell `dep` to ignore that directory, adding the following to the `Gopkg.toml` file:

```toml
ignored = ["github.com/openshift/autoheal/tools*"]
```

That seems like a more correct solution, but in our initial tests it didn't solve the problem. In addition, even if it solves the problem, then the tests of the `junitreport`  tool would be executed in addition to the tests of the project itself, thus polluting the output:

```
ok  	github.com/openshift/autoheal/cmd/autoheal	1.452s	coverage: 11.8% of statements
ok  	github.com/openshift/autoheal/tools/junitreport/pkg/builder/flat	1.009s	coverage: 100.0% of statements
ok  	github.com/openshift/autoheal/tools/junitreport/pkg/builder/nested	1.008s	coverage: 98.5% of statements
ok  	github.com/openshift/autoheal/tools/junitreport/pkg/parser/oscmd	1.103s	coverage: 100.0% of statements
ok  	github.com/openshift/autoheal/tools/junitreport/pkg/parser/stack	1.009s	coverage: 17.2% of statements
```

The optimal solution would preserve the test files, wouldn't add the `junitreport` project or its dependencies to the `vendor` directory and wouldn't run the `junitreport` tests together with the project tests. We should try to find that solution.

**Comment by jhernand** [comment]
The first attempt to address this issue is #16.

**Comment by ironcladlou** [comment]
The way I see it, the "tools" code is actually a completely self contained Go project with its own dependency tree. Here are two ways I can think of that this could work less invasively:

* If tools doesn't actually need to compile any tools stuff at runtime (and this would include runtime compilation indirectly via `go run`), then the installation procedure for tools could use a compilation process to ensure everything in the project tools directory has no external dependencies
* If tools absolutely must compile stuff at runtime, the tools directory should be a self-contained GOPATH, and all tools dependencies should be vendored with in it.

Other ideas?

**Comment by ironcladlou** [comment]
Whoops, I meant to put that comment an in issue against the release tools themselves. I think first I'd like to actually come up with a repeatable "example" project to help frame the discussion and test solutions.
