### ISSUE TITLE
Integrate with standard build/release tooling

### ISSUE THREAD

**Issue by ironcladlou** [openshift/autoheal#2]
1. Make a commit with the unmodified [boilerplate](https://github.com/openshift/release/tree/master/tools/hack/golang) stuff ([example](https://github.com/openshift/monitor-project-lifecycle/commit/6a3a0c15f070ac11968583e43bcdc625d180d5fa))
2. Update the boilerplate to make your component buildable ([example](https://github.com/openshift/monitor-project-lifecycle/commit/f573f617a3aff7cbb6f7fb6e1e5b4f9a6d0b3388))

**Comment by jhernand** [comment]
This is addressed by #4.
