### ISSUE TITLE
Make `server` the default command for autoheal cli

### ISSUE THREAD

**Issue by zgalor** [openshift/autoheal#22]
Today the CLI usage of autoheal service has the following interface:
```
Usage:
  autoheal [command]

Available Commands:
  help        Help about any command
  server      Starts the auto-heal server
```

Since running autoheal as a server would be the default widely usage, I think a simpler interface would be making `server` command the default and turn `help` command to a flag `--help`.

@jhernand @elad661 @moolitayer @ironcladlou your thoughts on this?

**Comment by moolitayer** [comment]
I agree, especially while we have only the `server` command

While we are on this subject, I think we are not using `cli` according to conventions.
The `cli` package (and dir) should be reserved to real command line interfaces (which we currently do not have here). I think our main package should be called something like `server` or `api`.

autoheal is a background server process, not a command line tool but this is not really important in any practical sense.

**Comment by jhernand** [comment]
I guess that you mean `cmd`, not `cli`. Putting the binaries inside the `cmd` directory is a common practice, no matter if they are intended to be used in the command line or something else. For example, the source of the Kubernetes API server lives in a `cmd/kube-apiserver` directory.

Having the `server` command is very convenient if you want to add other commands later. For example, we could want to add a `check` command to just check the configuration:

```
$ autoheal check --config-file=my.yml
```

So, in my opinion, we should keep things as they are, and close this issue.

**Comment by jhernand** [comment]
Closing for now, may re-open in the future.

**Comment by moolitayer** [comment]
I'm convinced @jhernand. I hijacked this issue to a different direction then it was created for: whether to have the server command default or not. I think that means assuming `server` if non provided if I understand correctly. I still think that makes sense but am not sure how complicated it is to do and if we should put time into that right now.
