### ISSUE TITLE
Adjust autoheal to breaking auth API changes in AWX 3.3

### ISSUE THREAD

**Issue by moolitayer** [openshift/autoheal#25]
Currently we working with Ansible Tower 3.2. in version 3.3, the way we used to do authentication against the API server is dropped and we should adapt (either support only the new way or both).

See:
[Announcement - has links for several related docs](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/awx-project/kjlXPyc2YwE/5Zxi8PGFAgAJ;context-place=msg/awx-project/ei61pBqAT5I/FVjb4JzKCgAJ)
https://github.com/ansible/awx/pull/904

Originally mentioned in:
https://github.com/openshift/autoheal/pull/23

**Comment by moolitayer** [comment]
I'm currently working on this issue. It will allow developing against AWX master (`devel`)

**Comment by jhernand** [comment]
@moolitayer I'd suggest to first try to implement a simple solution: add support for specifying directly the token instead of the user name and password:

```go
// Get the token from the secret:
token := ...

// Create the connection:
connect, err := awx.ConnectionBuilder().
  Address(...).
  Proxy(...).
  Token(token).
  Build()
```

That token would then need to be created manually in the AWX UI. This is assuming that the token is long lived, I am not 100% sure about that.

**Comment by rooftopcellist** [comment]
The token expiration time can be changed (currently only by manually changing the setting), but it defaults to 1000 years, which should be sufficiently long-lived.

**Comment by jhernand** [comment]
Great, thanks for the input @rooftopcellist. Any chances you can take a look at the #26? That is the pull request where @moolitayer is implementing authentication using personal access tokens. No need to get into the details, just check that we are moving in the right direction.

**Comment by rooftopcellist** [comment]
@jhernand The general approach of trying the AuthToken endpoint first and using the OAuth2 token if not should work.  For tower-cli (which also uses personal access tokens -- [here](https://github.com/ansible/tower-cli/pull/490/files#diff-6c200526bd6b171b824c81fc92924801R222)), we used a similar approach.  The only main difference afaik is that the existance of the `api/o` endpoint is checked when tower-cli starts and saved to determine which authentication method to use ([here](https://github.com/ansible/tower-cli/blob/9e57e0be580a73d94833c3932eed8694e2dbe4e8/tower_cli/utils/__init__.py#L39)).

**Comment by jhernand** [comment]
Thank you very much @rooftopcellist, that is the advice that we needed. @moolitayer do you think we can add the check of `api/o` to this pull request? If it is easy I'd do it, if not just merge as is and open an issue so that we remember to do it in the future.

**Comment by moolitayer** [comment]
Thanks @rooftopcellist!
@jhernand I prefer to leave the changes to another pull request if this one is ready to go.
Created https://github.com/openshift/autoheal/issues/29 to track this issue

**Comment by kruge002** [comment]
The 1000 year lifetime issue of the OAuth2 tokens can be fixed by a PATCH request to /api/v2/settings/authentication/. For more info see https://github.com/ansible/awx/issues/21#issuecomment-392884697
