### ISSUE TITLE
After unmarshling, rules have no name 

### ISSUE THREAD

**Issue by moolitayer** [openshift/autoheal#35]
Log has:
```
I0403 19:00:11.428969   15651 rules_worker.go:83] Rule '' was added
```

Not sure why this is suddenly happening. I have seen it on master with the default configuration

**Comment by jhernand** [comment]
This is a side effect of #28. Looks like Viper doesn't understand the `json:` tags that are used in the definitions of Kubernetes API objecs, which are used to define the rules. I think we need to revert #28, and maybe re-apply it once we have a solution. @nimrodshn can you submit a pull request to revert #28?

**Comment by jhernand** [comment]
@moolitayer meanwhile, in your local environment, just revert the problematic commit:

```
git revert 5b8a218ca48a43ff07c10e567937842902cad13f
```

**Comment by jhernand** [comment]
Assigned to myself because I can't assign @nimrodshn, but he is the real assignee.

**Comment by nimrodshn** [comment]
@jhernand  @moolitayer  on it.
