### ISSUE TITLE
Use OpenShift Go client

### ISSUE THREAD

**Issue by jhernand** [openshift/autoheal#40]
Currently the auto-heal service uses the Kubernetes Go client in order to retrieve secrets. It should use the [OpenShift Go client](https://github.com/openshift/client-go) instead.

**Comment by zgalor** [comment]
@jhernand why not stay with Kubernetes Go client?

**Comment by jhernand** [comment]
The reasoning is that the Kubernetes Go client may eventually have some incompatibility (or limitation) with the OpenShift cluster where the auto-heal service is intended to run. For example, if we wanted to use the OpenShift templating API from the auto-heal service (very unlikely) we wound't be able with the Kubernetes client, because there is no such API in Kubernetes.

Note that the Kubernetes and OpenShift go clients are almost exactly the same, just different package names (in theory), so this isn't a big change (again in theory, as dependencies are always tricky).

**Comment by jhernand** [comment]
I am assigning this to myself because I can't assign @zeari, but he is the real assignee.

**Comment by zeari** [comment]
As far as I can tell https://github.com/openshift/client-go doesnt have the option to get secrets.
getting k8s entities is done with the same k8s code that we use and the openshift go client only has code that has to do with openshift specific entities(builds, routes, etc).

I could be wrong though. Im still new at golang and the only example there is https://github.com/openshift/client-go/blob/master/examples/build/main.go

**Comment by jhernand** [comment]
Thanks for clarifying this @zeari, I was completely wrong. I am closing this issue.
