### ISSUE TITLE
Use etcd to and an API server to manage the healing rules

### ISSUE THREAD

**Issue by jhernand** [openshift/autoheal#85]
Currently the healing rules are stored in the configuration file of the auto-heal service. This is OK when there only a few rules, and when reconfiguring the auto-heal service to add/remove/modify healing rules isn't frequent. But to be really useful the auto-heal service should be very easy to reconfigure, because problems and their temporary solutions are very dynamic.

One possible solution to make the auto-heal service more dynamicv is to create an API server that manages the healing rules, storing them in an etcd database. This would allow other components to add/remove/modify healing rules via this API, without having to change the configuration of the auto-heal service directly. We could even build a GUI on top of that API, to allow human users to add/remove/modify healing rules manually.

Initially this API server doesn't need to be integrated with the rest of API servers of the cluster, but it could, in the future.

I have created #84 to explore this.

**Comment by moolitayer** [comment]
Version controlled heals in private repositories is consistent with how the ops worked in openshift-tools.
Maybe we should mix this with https://github.com/openshift/autoheal/issues/86 somehow? - Creating heals from the config file or taking existing ones from SCM?

Can we get to a situation where there is only one file to update when adding a new heal?
