### ISSUE TITLE
Automatically create AWX projects and job templates

### ISSUE THREAD

**Issue by jhernand** [openshift/autoheal#86]
Currently when a healing rule specifies a job template it has to exist in advance, the administrator of the AWX server needs to create it before creating the healing rule. Instead of that, the auto-heal service could manage its own git repository, and it could automatically create the job template, and playbook when the rule is added. For example, the healing rule could be defined like this:

```yaml
apiVersion: autoheal.openshift.io/v1alpha2
kind: HealingRule
metadata:
  name: my-rule
labels:
  alertname: "MyAlert"
awxJob:
  template: "My template"
  extraVars:
    instance: {{ $labels.instance }}
  playbook: |+
    The text of the playbook ...
```

When this rule is added to the configuration the auto-heal service should take the text of the playbook and commit it to its own git repository. Then it could also create the `My template` job template in the AWX server, if it doesn't exist yet, using the committed playbook.

The location and credentials of the git repository could then be part of the global configuration of the auto-heal service:

```yaml
git:
  address: git://github.com/myuser/myrepo
  credentials:
    username: ...
    password:
```

Or we could run a small git repository within the auto-heal service pod.

In order to create the templates (and maybe other objects) in the AWX server the auto-heal service should have the credentials of an AWX user with the required permissions, probably different to the one used to run the jobs. This should also go in the global configuration of the service, for example:

```yaml
awx:
  adminCredentials:
    username: "admin"
    password: ...
```

**Comment by moolitayer** [comment]
Let me see if I understand @jhernand. We will be creating a new project looking at the SCM defined in the configuration and pushing the contents of our healing rules to that repository?

I think `template` would need a name - a common use case might be a newly setup AWX server with a repo that already has heals (files) in it. We could also generate the name ourselves but maybe that would be less clear to users.

If we have access to the project SCM and we see an existing playbooks with a different content then the healing rule do we care? What if the template is defined but with a different content?

Do we support external updates of the SCM?

BTW we must also specify an inventory when creating a job template so we might need that in the configuration as well.

**Comment by jhernand** [comment]
Yes, if we see that there isn't a project with the name that we expect, then we create a new one using the SCM configuration that we have in the auto-heal service configuration.

Then, when we are asked to run a job from a job template that doesn't exist in the AWX server, and if we are explicitly given the text of a playbook, we commit that playbook to the git repository (if needed, may already be there) and create the new job template using the name of that playbook.

This idea of committing automatically things to the git repository only makes sense if that repository is something that we consider temporary, and that is managed and owned by the auto-heal service. If it is an existing git repository then we should limit ourselves to check that it contains what we need, or just do nothing, like we do today.

**Comment by jhernand** [comment]
To simplify things we can start without the git commiting part: we create the project and the job templates if they don't exist, with the information taken from the auto-heal configuration, but without including the playbook text in the healing rule.

**Comment by cben** [comment]
What if we flip this on its head?  Suppose both AWX and autoheal pulled from same git repo (AWX by builtin ability, autoheal by git-sync sidecar).
Suppose autoheal config & rules go in a different directory (that AWX ignores), and refer to playbooks by name.
What's missing then to ability to create new rule & heal by single git commit?

- IIUC, one git repo for all heals means we use one AWX "project".
- But there can be many AWX "jobs", one per playbook.
- autoheal would reload config when git-sync sidecar updates the local checkout.
- I think the missing piece is defining the AWX job.
  - autoheal could notice a missing job and create it.
  - in principle, this might belong upstream in AWX itself — ability to have projects where jobs auto-appear, one per playbook file?

**Comment by moolitayer** [comment]
> To simplify things we can start without the git commiting part: we create the project and the job templates if they don't exist, with the information taken from the auto-heal configuration, but without including the playbook text in the healing rule.

That makes sense. Let's see if I understand, for stage 1, under `awxJob` we would have `template: "X"`
and optional name of the playbook(like `playbookName`). If `playbookName` var exists and `template: "X"` does  not exist we create the template `"X"` running playbook `playbookName`. 
```
awxJob:
  template: "My template"
  extraVars:
    instance: {{ $labels.instance }}
  playbookName: "some-heal.yml"
```

Then on stage 2 we can include some combination of `playbookName` and `playbook` (for actual content)

@jhernand does that makes sense?



> What if we flip this on its head? Suppose both AWX and autoheal pulled from same git repo (AWX by builtin ability, autoheal by git-sync sidecar).
> Suppose autoheal config & rules go in a different directory (that AWX ignores), and refer to playbooks by name.

@cben with the idea suggested here we would be able to update only one file for a healing rule. We would also be able to use one repository or two separate ones.
