### ISSUE TITLE
Verify AWX `PROMPT ON LAUNCH` option before running

### ISSUE THREAD

**Issue by zgalor** [openshift/autoheal#89]
In order to support passing `limit` and `extraVars` to AWX template, the `PROMPT ON LAUNCH` option must be checked.

We should verify it is checked for each of the fields in 2 stages:
1. When the rule is processed
2. Before the template is launched

If one of those fields is defined in the rule, but not set to `PROMPT ON LAUNCH` in the AWX template, we should log a warning to the user.

**Comment by moolitayer** [comment]
Can you elaborate a bit more on what `PROMPT ON LAUNCH` is @zgalor ?

**Comment by moolitayer** [comment]
OK I see https://github.com/openshift/autoheal/pull/90/files#diff-04c6e90faac2675aa89e2176d2eec7d8L247

> 1. When the rule is processed

What if awx is down while we are parsing configuration, do we want to abort loading it? will we retry?

I think writing a clear error message as you suggested in 2. is best.
