### ISSUE TITLE
Send logs to stdout or stderr by default

### ISSUE THREAD

**Issue by jhernand** [openshift/autoheal#9]
Currently the `autoheal` application doesn't send the logs
to `stderr` or `stdout` by default. To do so it requires the
`-logalsotostderr` command line option. We should change
that so that logs go to `stderr` and `stdout` by default, without
requiring any option.

**Comment by yaacov** [comment]
we do not have a `-logalsotostderr` ? 
does this refer to `-logtostderr` ?

**Comment by yaacov** [comment]
Taking this one, didn't understand it it before :-)

**Comment by yaacov** [comment]
@zeari is realy taking this one, but his not on openshift assignees yet.
